// Autogenerated by @nobush/cli-tools react-svg converter
import type React from 'react';

export interface HeartProps extends React.SVGProps<SVGSVGElement> {}

export const Heart: React.FC<HeartProps> = (props) => (
  <svg xmlns="http://www.w3.org/2000/svg" viewBox='2 2 124 124' {...props}>
    <path d="M90.35 16.05c-11.66 0-21.81 6.97-26.35 17.06-4.54-10.08-14.69-17.06-26.35-17.06-15.92 0-28.87 12.96-28.87 28.88 0 35.9 51.79 65.46 54 66.7.38.21.79.32 1.21.32.42 0 .84-.11 1.21-.32 2.2-1.24 54.01-30.8 54.01-66.7.01-15.92-12.94-28.88-28.86-28.88z" style={{"fill":"#e25da0"}}/>
  </svg>

);

export default Heart;
